<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employee InformationEmployee NameEmploy_3710a1</name>
   <tag></tag>
   <elementGuidId>87ab4fb2-eb07-492d-81cb-6148f82459c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a8eaa37-83dd-4e2b-82db-eb6c7b801b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>b2b84e11-c039-41d3-b405-5698591874a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee InformationEmployee NameEmployee IdEmployment Status-- Select --IncludeCurrent Employees OnlySupervisor NameJob Title-- Select --Sub Unit-- Select -- Reset  Search  Add  (52) Records FoundIdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0259Edgar RiverQuispe0271Edgar RiverQuispe0257Edgar RiverQuispe0276Edgar RiverQuispe0270Edgar RiverQuispe0266Edgar RiverQuispe0261Edgar RiverQuispe0275Edgar RiverQuispe0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman Resourcestest Test0235Goutam GaneshSales RepresentativeFull-Time PermanentSales0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman Resourcestest Test0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOps0254Jyoti Jadhav028312987Kanchan shere027812987Kanchan shere028212987Kanchan shere028712987Kanchan shere027912987Kanchan shere0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman Resourcestest Test0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOps0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSales0074Nina PatelPre-Sales CoordinatorFull-Time ContractSales0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0264peppa Pig0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil0262Rahul k3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman Resourcestest Test0286Shreyas P0024test TestHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0267TEST123 Katalon1020TestFirstName TestMiddleNameTestLastName12</value>
      <webElementGuid>0ce8680f-c286-4561-be6b-42b8569a71fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>0263fc0b-521c-4058-994e-32983fbd011d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>62f8988a-c663-484b-bba6-ca3c3902f964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::div[4]</value>
      <webElementGuid>a960a397-6fe1-44a5-a26f-e4ef9888510a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>b364d2db-e377-4fa8-8c74-ecab23f7be92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Employee InformationEmployee NameEmployee IdEmployment Status-- Select --IncludeCurrent Employees OnlySupervisor NameJob Title-- Select --Sub Unit-- Select -- Reset  Search  Add  (52) Records FoundIdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0259Edgar RiverQuispe0271Edgar RiverQuispe0257Edgar RiverQuispe0276Edgar RiverQuispe0270Edgar RiverQuispe0266Edgar RiverQuispe0261Edgar RiverQuispe0275Edgar RiverQuispe0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman Resourcestest Test0235Goutam GaneshSales RepresentativeFull-Time PermanentSales0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman Resourcestest Test0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOps0254Jyoti Jadhav028312987Kanchan shere027812987Kanchan shere028212987Kanchan shere028712987Kanchan shere027912987Kanchan shere0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman Resourcestest Test0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOps0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSales0074Nina PatelPre-Sales CoordinatorFull-Time ContractSales0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0264peppa Pig0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil0262Rahul k3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman Resourcestest Test0286Shreyas P0024test TestHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0267TEST123 Katalon1020TestFirstName TestMiddleNameTestLastName12' or . = 'Employee InformationEmployee NameEmployee IdEmployment Status-- Select --IncludeCurrent Employees OnlySupervisor NameJob Title-- Select --Sub Unit-- Select -- Reset  Search  Add  (52) Records FoundIdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0259Edgar RiverQuispe0271Edgar RiverQuispe0257Edgar RiverQuispe0276Edgar RiverQuispe0270Edgar RiverQuispe0266Edgar RiverQuispe0261Edgar RiverQuispe0275Edgar RiverQuispe0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman Resourcestest Test0235Goutam GaneshSales RepresentativeFull-Time PermanentSales0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman Resourcestest Test0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOps0254Jyoti Jadhav028312987Kanchan shere027812987Kanchan shere028212987Kanchan shere028712987Kanchan shere027912987Kanchan shere0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman Resourcestest Test0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOps0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSales0074Nina PatelPre-Sales CoordinatorFull-Time ContractSales0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0264peppa Pig0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil0262Rahul k3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman Resourcestest Test0286Shreyas P0024test TestHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0267TEST123 Katalon1020TestFirstName TestMiddleNameTestLastName12')]</value>
      <webElementGuid>0d0feae1-0ff7-40fc-8de4-6e710dca9069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
