<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit Pay GradeName  Required Cancel  Sa_e922bf</name>
   <tag></tag>
   <elementGuidId>eca97193-d370-4494-baf1-5bbb3ad47263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b458de06-0fc7-4f0e-803b-a59f512b29b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>c6957f0e-28e1-428d-8646-5c0cffbfa81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Pay GradeName * Required Cancel  Save Add CurrencyCurrencyAED - Utd. Arab Emir. DirhamMinimum SalaryMaximum Salary * Required Cancel  Save Currencies Add No Records FoundCurrencyMinimum SalaryMaximum SalaryActions</value>
      <webElementGuid>640f9325-f67c-41d1-888e-11652d28c98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>3b52c458-98af-4654-b262-2c474f90797b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>dbfd26ff-4c0e-4bba-8ab9-c04fbdf81aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[4]</value>
      <webElementGuid>7058fbe0-47b8-453a-b0b2-0682045832d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifications'])[1]/following::div[4]</value>
      <webElementGuid>30692bd1-c7c1-4cca-abfd-a70530e0dcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>642dfe07-a786-43b0-b4cd-c7389d5b5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit Pay GradeName * Required Cancel  Save Add CurrencyCurrencyAED - Utd. Arab Emir. DirhamMinimum SalaryMaximum Salary * Required Cancel  Save Currencies Add No Records FoundCurrencyMinimum SalaryMaximum SalaryActions' or . = 'Edit Pay GradeName * Required Cancel  Save Add CurrencyCurrencyAED - Utd. Arab Emir. DirhamMinimum SalaryMaximum Salary * Required Cancel  Save Currencies Add No Records FoundCurrencyMinimum SalaryMaximum SalaryActions')]</value>
      <webElementGuid>a243aa33-ec02-471b-b93f-664ddafa76fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
